### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by peedeeee** [AmateurHotShot/reddit-youtube-v2#1]
Title: already have....
[Reddit] g8f4b3sfk4q81: Downloading m3u8 information
[Reddit] g8f4b3sfk4q81: Downloading MPD manifest
WARNING: You have requested multiple formats but ffmpeg or avconv are not installed. The formats won't be merged.
[download] Shorts\Downloaded\03-29-22\t3_tq941b.fhls-1489.mp4 has already been downloaded
[download] 100% of 4.45MiB
[download] Shorts\Downloaded\03-29-22\t3_tq941b.mp4.fdash-audio_0_115598 has already been downloaded
[download] 100% of 391.96KiB
Get Length: ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 Shorts/Downloaded/03-29-22/t3_tq941b.mp4
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\reddit-youtube-v2-master\main.py", line 9, in <module>
    find_videos.GetPosts(subs, post_limit=post_limit).download_posts()
  File "C:\Users\Administrator\Desktop\reddit-youtube-v2-master\find_videos.py", line 44, in download_posts
    GetPosts.write_to_json(submission, sub, count_downloads)
  File "C:\Users\Administrator\Desktop\reddit-youtube-v2-master\find_videos.py", line 104, in write_to_json
    clip_length = GetPosts.get_length(f"Shorts/Downloaded/{date_downloaded}/{submission.name}.mp4")
  File "C:\Users\Administrator\Desktop\reddit-youtube-v2-master\find_videos.py", line 78, in get_length
    result = subprocess.run(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by peedeeee** [comment]
What is the format of shorts_post_info.json?
